'use client';
import { useMemo, useState } from 'react';
import { Check, Download, FileCheck2, Lock, RefreshCw, Send, ShieldCheck, XCircle } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Exam=any; type Sheet=any; type Mark=any; type Result=any;
const EXAM_TYPES=[
 {value:'first_terminal',label:'1st Terminal',name:'1st Terminal Examination'},
 {value:'second_terminal',label:'2nd Terminal',name:'2nd Terminal Examination'},
 {value:'third_terminal',label:'3rd Terminal',name:'3rd Terminal Examination'},
 {value:'final',label:'Final',name:'Final Examination'},
 {value:'monthly',label:'Monthly Test',name:'Monthly Test'},
 {value:'midterm',label:'Mid-Term',name:'Mid-Term Examination'},
 {value:'preboard',label:'Pre-Board',name:'Pre-Board Examination'},
];
function grade(p:number){return p>=90?'A+':p>=80?'A':p>=70?'B+':p>=60?'B':p>=50?'C+':p>=40?'C':'F'}
export default function ExaminationsManagement({role,exams:initialExams,sheets:initialSheets,marks:initialMarks,results:initialResults,classes,sections,subjects,years}:{role:string;exams:Exam[];sheets:Sheet[];marks:Mark[];results:Result[];classes:any[];sections:any[];subjects:any[];years:any[]}){
 const supabase=createClient(); const [exams,setExams]=useState(initialExams); const [sheets,setSheets]=useState(initialSheets); const [marks,setMarks]=useState(initialMarks); const [results,setResults]=useState(initialResults); const [selected,setSelected]=useState(initialExams[0]?.id||''); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('');
 const current=exams.find(e=>e.id===selected)||exams[0]; const [form,setForm]=useState({year:years.find(y=>y.is_current)?.id||years[0]?.id||'',term:'first_terminal',name:'1st Terminal Examination',starts_on:'',ends_on:'',deadline:''});
 const visibleSheets=useMemo(()=>sheets.filter(s=>s.examination_id===current?.id),[sheets,current]); const visibleResults=useMemo(()=>results.filter(r=>r.examination_id===current?.id),[results,current]);
 const mySheets=role==='teacher'?visibleSheets:visibleSheets;
 async function refresh(examId?:string){if(!supabase)return;const id=examId||current?.id;
  const [{data:e},{data:sh},{data:r}]=await Promise.all([
   supabase.from('examinations').select('id,academic_year_id,term,name,starts_on,ends_on,marks_deadline,status,created_at').order('starts_on',{ascending:false,nullsFirst:false}),
   id?supabase.from('exam_mark_sheets').select('id,examination_id,class_id,section_id,subject_id,teacher_id,status,submitted_at,verified_at,review_note,classes(name,grade),sections(name),subjects(name,code),profiles!exam_mark_sheets_teacher_id_fkey(full_name)').eq('examination_id',id):Promise.resolve({data:[] as any[]}),
   id?supabase.from('exam_results').select('id,examination_id,student_id,class_id,section_id,total_marks,total_max_marks,percentage,grade,rank,is_published,profiles!exam_results_student_id_fkey(full_name),classes(name),sections(name)').eq('examination_id',id).order('rank'):Promise.resolve({data:[] as any[]}),
  ]);
  setExams(e||[]);setSheets(sh||[]);setResults(r||[]);
  const ids=((sh as any[])||[]).map((x:any)=>x.id);
  if(ids.length){const {data:m}=await supabase.from('exam_marks').select('id,mark_sheet_id,student_id,enrollment_id,marks,max_marks,remarks,profiles!exam_marks_student_id_fkey(full_name)').in('mark_sheet_id',ids);setMarks(m||[])}else setMarks([])}
 async function createExam(){if(!supabase)return;setBusy(true);setNotice('');
  const {data:created,error}=await supabase.from('examinations').insert({academic_year_id:form.year,term:form.term,name:form.name,starts_on:form.starts_on||null,ends_on:form.ends_on||null,marks_deadline:form.deadline||null,created_by:(await supabase.auth.getSession()).data.session?.user?.id}).select('id').single();
  if(error){setNotice(error.code==='23505'?'An examination with this name already exists in this academic year. Change the name (for example "Baisakh Monthly Test") and try again.':error.message)}
  else{setNotice('Examination created. Now click "Open mark entry" so teachers can enter marks.');if(created){setSelected(created.id);await refresh(created.id)}else await refresh()}
  setBusy(false)}
 async function openEntry(){if(!supabase||!current)return;setBusy(true);const {data,error}=await supabase.rpc('open_exam_mark_entry',{p_exam_id:current.id});setNotice(error?.message||`Mark-entry sheets opened. ${data??0} student rows prepared.`);await refresh();setBusy(false)}
 async function review(id:string,approve:boolean){if(!supabase)return;const note=approve?'Verified by admin':prompt('Reason for correction:')||'';setBusy(true);const {error}=await supabase.rpc('review_exam_mark_sheet',{p_mark_sheet_id:id,p_approve:approve,p_note:note});setNotice(error?.message|| (approve?'Mark sheet verified.':'Changes requested.'));await refresh();setBusy(false)}
 async function generate(){if(!supabase||!current)return;setBusy(true);const {data,error}=await supabase.rpc('generate_exam_results',{p_exam_id:current.id});setNotice(error?.message||`Generated results for ${data??0} students.`);await refresh();setBusy(false)}
 async function publish(classId:string,sectionId:string,on:boolean){if(!supabase||!current)return;setBusy(true);const {error}=await supabase.rpc('publish_exam_results',{p_exam_id:current.id,p_class_id:classId,p_section_id:sectionId,p_publish:on});setNotice(error?.message||(on?'Results published.':'Results unpublished.'));await refresh();setBusy(false)}
 async function submit(id:string){if(!supabase)return;setBusy(true);const {error}=await supabase.rpc('submit_exam_mark_sheet',{p_mark_sheet_id:id});setNotice(error?.message||'Submitted for admin verification.');await refresh();setBusy(false)}
 async function saveMarks(sheetId:string){if(!supabase)return;const sheetMarks=marks.filter(m=>m.mark_sheet_id===sheetId);setBusy(true);
  // PERFORMANCE: the whole sheet is saved in ONE database call (was: one call per student, one after another).
  const payload=sheetMarks.map(m=>({id:m.id,marks:m.marks===''||m.marks==null?null:Number(m.marks),remarks:m.remarks||null}));
  let {error}=await supabase.rpc('save_exam_marks',{p_marks:payload});
  if(error&&(error.code==='PGRST202'||/save_exam_marks/i.test(error.message))){
   // The SQL function has not been installed yet (010_performance.sql) - fall back to saving all rows at the same time.
   const results=await Promise.all(payload.map(m=>supabase.from('exam_marks').update({marks:m.marks,remarks:m.remarks}).eq('id',m.id)));
   error=results.find(x=>x.error)?.error||null;
  }
  if(error){setNotice(error.message);setBusy(false);return}
  setNotice('Marks saved. Submit the sheet when complete.');await refresh();setBusy(false)}
 function setMark(id:string,value:string){setMarks(ms=>ms.map(m=>m.id===id?{...m,marks:value}:m))}
 function downloadCSV(){const rows=[['Rank','Student','Class','Section','Total','Maximum','Percentage','Grade','Published'],...visibleResults.map(r=>[r.rank,r.profiles?.full_name||'',r.classes?.name||'',r.sections?.name||'',r.total_marks,r.total_max_marks,r.percentage,r.grade,r.is_published?'Yes':'No'])];const csv=rows.map(x=>x.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${current?.name||'results'}-results.csv`;a.click();URL.revokeObjectURL(a.href)}
 const resultGroups=useMemo(()=>{const map=new Map<string,any>();for(const r of visibleResults){const k=`${r.class_id}:${r.section_id}`;(map.get(k)||map.set(k,{class_id:r.class_id,section_id:r.section_id,className:r.classes?.name||'',sectionName:r.sections?.name||'',published:r.is_published}).get(k)).published ||= r.is_published}return [...map.values()]},[visibleResults]);
 return <div className="exam-space">
 {role==='admin'&&<section className="card exam-create"><div className="panel-head"><div><span className="section-kicker"><ShieldCheck size={15}/> ADMIN CONTROL</span><h2>Set up an examination</h2><p>Create the exam window before teachers enter marks.</p></div></div><div className="form-grid five"><label>Academic year<select value={form.year} onChange={e=>setForm({...form,year:e.target.value})}>{years.map(y=><option key={y.id} value={y.id}>{y.name}</option>)}</select></label><label>Exam type<select value={form.term} onChange={e=>setForm({...form,term:e.target.value,name:EXAM_TYPES.find(t=>t.value===e.target.value)?.name||form.name})}>{EXAM_TYPES.map(t=><option key={t.value} value={t.value}>{t.label}</option>)}</select></label><label>Exam name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Start<input type="date" value={form.starts_on} onChange={e=>setForm({...form,starts_on:e.target.value})}/></label><label>End<input type="date" value={form.ends_on} onChange={e=>setForm({...form,ends_on:e.target.value})}/></label><label>Marks deadline<input type="datetime-local" value={form.deadline} onChange={e=>setForm({...form,deadline:e.target.value})}/></label></div>{notice&&<div className="notice">{notice}</div>}<button className="primary-btn" disabled={busy||!form.year} onClick={createExam}>Create examination</button></section>}
 <section className="card exam-toolbar"><div><span className="section-kicker">EXAMINATION WORKSPACE</span><h2>{current?.name||'No examination selected'}</h2></div><div className="exam-actions"><select value={current?.id||''} onChange={e=>{setSelected(e.target.value);refresh(e.target.value)}}>{exams.map(e=><option key={e.id} value={e.id}>{e.name} · {e.status}</option>)}</select>{role==='admin'&&<><button className="secondary-btn" disabled={!current||busy} onClick={openEntry}><RefreshCw size={15}/> Open mark entry</button><button className="secondary-btn" disabled={!current||busy} onClick={generate}><FileCheck2 size={15}/> Generate results</button><button className="secondary-btn" disabled={!visibleResults.length} onClick={downloadCSV}><Download size={15}/> CSV</button></>}</div></section>
 {notice&&role!=='admin'&&<div className="notice">{notice}</div>}
 <section className="exam-grid"><div className="card"><div className="panel-head"><div><span className="section-kicker">MARK ENTRY</span><h3>{role==='teacher'?'Your mark sheets':'Teacher submissions'}</h3></div><span className="status neutral">{visibleSheets.filter(s=>s.status==='verified').length}/{visibleSheets.length} verified</span></div><div className="exam-table">{mySheets.length===0?<div className="empty-panel"><h3>{current?.status==='draft'?'Mark entry not opened':'No mark sheets available'}</h3><p>{role==='admin'?'Open mark entry to prepare teacher sheets.':'Ask the admin to open mark entry for this examination.'}</p></div>:mySheets.map(s=>{const sheetMarks=marks.filter(m=>m.mark_sheet_id===s.id);return <div className="exam-sheet" key={s.id}><div className="exam-row"><div><strong>{s.classes?.name||''} · {s.sections?.name||''}</strong><span>{s.subjects?.name||''} · {s.profiles?.full_name||'Teacher'}</span></div><span className={`status ${s.status}`}>{s.status.replace('_',' ')}</span><div className="row-actions">{role==='teacher'&&['draft','changes_requested'].includes(s.status)&&<><button className="secondary-btn" onClick={()=>saveMarks(s.id)}><Check size={13}/> Save</button><button className="primary-btn small" onClick={()=>submit(s.id)}><Send size={13}/> Submit</button></>}{role==='admin'&&s.status==='submitted'&&<><button className="approve-btn" onClick={()=>review(s.id,true)}><Check size={13}/> Verify</button><button className="reject-btn" onClick={()=>review(s.id,false)}><XCircle size={13}/> Return</button></>}</div></div>{role==='teacher'&&['draft','changes_requested'].includes(s.status)&&<div className="marks-editor">{sheetMarks.map(m=><div className="mark-cell" key={m.id}><div><strong>{m.profiles?.full_name||'Student'}</strong><span>Max {m.max_marks}</span></div><input type="number" min="0" max={m.max_marks} step="0.5" value={m.marks??''} onChange={e=>setMark(m.id,e.target.value)} placeholder="Marks"/></div>)}</div>}{role==='admin'&&s.status==='changes_requested'&&s.review_note&&<div className="review-note"><strong>Correction note:</strong> {s.review_note}</div>}</div>})}</div></div>
 <div className="card"><div className="panel-head"><div><span className="section-kicker">RESULTS</span><h3>Generated results</h3></div><span className="status approved">{visibleResults.length} students</span></div><div className="exam-table">{visibleResults.length===0?<div className="empty-panel"><h3>Results not generated</h3><p>Verify every mark sheet, then generate the result.</p></div>:<>{visibleResults.slice(0,50).map(r=><div className="result-row" key={r.id}><div className="rank-badge">#{r.rank}</div><div><strong>{r.profiles?.full_name||'Student'}</strong><span>{r.classes?.name||''} · {r.sections?.name||''}</span></div><strong>{r.percentage}%</strong><span className="grade-pill">{r.grade}</span><span className={`status ${r.is_published?'approved':'neutral'}`}>{r.is_published?'Published':'Private'}</span></div>)}{role!=='student'&&resultGroups.map(g=><div className="publish-row" key={g.class_id+g.section_id}><div><strong>{g.className} · {g.sectionName}</strong><span>Class result publication</span></div><button className={g.published?'secondary-btn':'primary-btn'} disabled={busy} onClick={()=>publish(g.class_id,g.section_id,!g.published)}>{g.published?<><Lock size={13}/> Unpublish</>:<><Check size={13}/> Publish</>}</button></div>)}</>}</div></div></section>
 </div>
}
