'use client';
import { useState } from 'react';
import { ArrowLeft,Mail,RefreshCw,Search,Trash2,UserCheck,UserPlus,Users,UserX } from 'lucide-react';
import Link from 'next/link';
import Sidebar from '@/components/sidebar';
import TeacherInviteForm from '@/components/admin/teacher-invite-form';
import { createClient } from '@/lib/supabase/client';
type Teacher={id:string;full_name:string;email:string|null;phone:string|null;is_active:boolean;created_at:string};
export default function TeachersManagement({initialTeachers}:{initialTeachers:Teacher[]}){const [teachers,setTeachers]=useState<Teacher[]>(initialTeachers),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[notice,setNotice]=useState(''),[noticeOk,setNoticeOk]=useState(true),[working,setWorking]=useState('');async function load(){const s=createClient();if(!s)return;setLoading(true);const {data}=await s.from('profiles').select('id,full_name,email,phone,is_active,created_at').eq('role','teacher').order('full_name');setTeachers(data||[]);setLoading(false)}function flash(text:string,ok:boolean){setNotice(text);setNoticeOk(ok)}
async function toggleActive(t:Teacher){const s=createClient();if(!s)return;setWorking(t.id);flash('',true);const next=!t.is_active;const {error}=await s.from('profiles').update({is_active:next}).eq('id',t.id).eq('role','teacher');setWorking('');if(error){flash(error.message,false);return}setTeachers(list=>list.map(x=>x.id===t.id?{...x,is_active:next}:x));flash(`${t.full_name} is now ${next?'active':'inactive'}.`,true)}
async function removeTeacher(t:Teacher){if(!window.confirm(`Permanently delete ${t.full_name}?\n\nTheir login will be removed and they will no longer be able to sign in. This cannot be undone.\n\n(If you only want to stop their access, use Deactivate instead.)`))return;setWorking(t.id);flash('',true);try{const res=await fetch('/api/admin/users',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:t.id})});const data=await res.json().catch(()=>({}));if(!res.ok){flash(data.error||'Could not delete this teacher.',false);return}setTeachers(list=>list.filter(x=>x.id!==t.id));flash(`${t.full_name} was deleted.`,true)}finally{setWorking('')}}
const filtered=teachers.filter(t=>(t.full_name+' '+(t.email||'')).toLowerCase().includes(q.toLowerCase()));return <div className="app-shell"><Sidebar/><main className="main"><div className="content"><div className="page-head"><div><Link href="/dashboard" className="back-link"><ArrowLeft size={16}/> Dashboard</Link><h1>Teachers</h1><p>Manage teaching staff, invitations and active status.</p></div><div className="security-chip"><Users size={16}/> {teachers.length} teachers</div></div><section className="panel form-panel"><div className="panel-head"><div><h3>Invite a teacher</h3><p>The teacher receives an email invitation to create their secure account.</p></div><UserPlus size={19}/></div><div className="panel-body"><TeacherInviteForm onDone={load}/></div></section><div className="toolbar"><div className="search wide"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search teacher name or email..."/></div><button className="secondary-btn" onClick={load}><RefreshCw size={16}/> Refresh</button></div>{notice&&<div className={noticeOk?'form-success':'form-error'} style={{marginBottom:12}}>{notice}</div>}<section className="panel"><div className="table-wrap"><div className="table-head teacher-head"><span>TEACHER</span><span>CONTACT</span><span>STATUS</span><span>JOINED</span><span>ACTIONS</span></div>{loading?<div className="loading-row">Loading teachers…</div>:filtered.map(t=><div className="table-row teacher-row" key={t.id}><div className="person-inline"><div className="avatar student">{t.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><strong>{t.full_name}</strong><span>Teacher</span></div></div><span className="muted"><Mail size={13}/>{t.email||'—'}</span><span className={'status '+(t.is_active?'approved':'pending')}>{t.is_active?'active':'inactive'}</span><span className="muted">{new Date(t.created_at).toLocaleDateString()}</span><div className="row-actions"><button className="mini-btn" disabled={working===t.id} onClick={()=>toggleActive(t)}>{t.is_active?<UserX size={14}/>:<UserCheck size={14}/>} {t.is_active?'Deactivate':'Activate'}</button><button className="mini-btn danger" disabled={working===t.id} onClick={()=>removeTeacher(t)}><Trash2 size={14}/> Delete</button></div></div>)}</div></section></div></main></div>}
